# Generated by Django 5.0.3 on 2024-03-16 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0004_alter_user_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_category_iditem_category',
            field=models.ForeignKey(db_column='item_category_iditem_category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Brewer_Cafe_And_Restro.itemcategory'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.ForeignKey(db_column='area_pincode', default='362205', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Brewer_Cafe_And_Restro.area'),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
