# Generated by Django 5.0.3 on 2024-03-16 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0005_alter_item_item_category_iditem_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('idsubcategory', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('subcategory_description', models.CharField(max_length=1000)),
                ('subcategory_image', models.ImageField(blank=True, null=True, upload_to='media/subcategory/')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='Brewer_Cafe_And_Restro.itemcategory')),
            ],
            options={
                'db_table': 'subcategory',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='item_category_iditem_category',
            field=models.ForeignKey(db_column='subcategory_idsubcategory', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Brewer_Cafe_And_Restro.subcategory'),
        ),
    ]
