# Generated by Django 5.0.3 on 2024-03-16 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brewer_Cafe_And_Restro', '0006_subcategory_alter_item_item_category_iditem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='restaurant_idrestaurant',
            field=models.ForeignKey(db_column='restaurant_idrestaurant', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Brewer_Cafe_And_Restro.restaurant'),
        ),
    ]
